### ISSUE TITLE
Refactoring T3TWIG

### ISSUE THREAD

**Issue by digedag** [DMKEBUSINESSGMBH/typo3-t3twig#6]
Ich finde das cObject T3TWIG sollte etwas umstruktiert werden und sich mehr an FLUIDTEMPLATE orientieren. Folgende Punkte sollten meiner Ansicht nach angepasst werden:

- Umbenennung in TWIGTEMPLATE
- Die Templatedatei sollte mit *file* konfiguriert werden
- Die Daten für den Twig-Context sollten unterhalb von *context* abgegeben werden

Das würde dann so aussehen:
```
page = PAGE
page.10 = TWIGTEMPLATE
page.10 {
  file = path/to/template.twig
  context {
    logo =< lib.page.logo
    menu =< lib.page.mymenu
  }
}
```

**Comment by rengaw83** [comment]
Eine Anlehnung an das FLUIDTEMPLATE ist meines Erachtens weitaus komplexer als obiges Beispiel.
Folgendes Beispiel wird oft verwendet, hat mit dem obigem nichts gemein::
```
lib.stdContent = FLUIDTEMPLATE
lib.stdContent {
    templateName = Default
    layoutRootPaths {
        10 = EXT:frontend/Resources/Private/Layouts
        20 = EXT:sitemodification/Resources/Private/Layouts
    }
    partialRootPaths {
        10 = EXT:frontend/Resources/Private/Partials
        20 = EXT:sitemodification/Resources/Private/Partials
    }
    templateRootPaths {
        10 = EXT:frontend/Resources/Private/Templates
        20 = EXT:sitemodification/Resources/Private/Templates
    }
    variables {
        foo = bar
    }
}
```
Das Template lässt sich bei Fluid über `templateName` / `templateRootPaths`, `template` oder `file` angeben.
Weiter müsste sich beim `context` bzw. den  `variables` um das Rendern der Libs bzw. ContentObjecte gekümmert werden. Dies allerdings nur, wenn diese im Template auch benötigt werden, um unnötiges, ggf. resourcehungriges Parsing zu vermeiden.

Die Umbenennung ist möglich, allerdings müssten dann die Bestandsprojekte angepasst werden, oder es gibt einen Alias.

Weiter baut das Twig cObject aktuell direkt auf den bestehenden Renderer von T3TWIG auf.
Dieser baut aus historischen Gründen auf rn_base auf und dessen template konfiguration.
Das Konfigurations-Array im cObject müsste dahingehend oder die rnbase basierenden Views auf die neue Konfiguration gemappt werden.

**Comment by digedag** [comment]
Also es geht mir nicht darum, das 1-zu-1 zum FLUIDTEMPLATE aufzubauen. In TYPO3 gibt es die Contentobjekte TEMPLATE und FLUIDTEMPLATE. Dann sollte das Objekt für Twig IMHO entsprechend auch TWIGTEMPLATE heißen. Und **file** ist meiner Ansicht nach auch der bessere Name für die Pfadangabe zur Datei. Kann ja auch als Alias hinzugefügt werden.

Die Werte für den Twig-Context sollten in der Struktur eine Ebene tiefer stehen, damit es keine Kollision zu anderen Angaben (template/file) gibt. Ob das dann **context** oder **variables** heißt, ist mir eigentlich egal. Hier würde man natürlich vorhandene Installationen anpassen müssen.
Das die Objekte immer gerendert werden müssen und eine Prüfung der Verwendung nicht möglich ist, liegt in der Natur der Sache. Aber eben auch in der Verantwortung des T3-Admins.

Die **templateRootPaths** sind bei Twig ja nicht relevant. Es gibt aber andere Konfigurationen für Twig, die später mal noch aufgenommen werden können.

**Comment by digedag** [comment]
Ich hab jetzt erstmal soweit drin und auch dokumentiert. Ein paar Dinge würde ich aber gern noch ausbauen, weil mir da zuviele unnötige "Fallbacks" drin sind.
Aber der Reihe nach. Das Contentobject heißt nun zusätzlich auch `TWIGTEMPLATE`. Die Template Datei sollte mit dem Attribut *file* angegeben werden. Das Attribute *template* mit allen seinen Fallbacks funktioniert aber immer noch. Die würde ich aber gern entfernen.

Die Daten für den Context werden nun unterhalb des Attributs `context` geladen. Wird dieses Attribut nicht gefunden, dann wird wie bisher der Inhalt von `cObj->data` flach in den Context gelegt. Das war's dann aber auch. Ist `context` dagegen vorhanden, dann werden die Daten wie oben beschrieben ausgewertet und dem Context hinzugefügt. Außerdem werden immer drei reservierte Datensätze eingebunden:
* **data** -> Der aktuelle Inhalt von `cObj->data`
* **current** -> Der Inhalt von `cObj->data[cObj->currentValKey]`
* **page** -> der Record der aktuellen Seite

Wie gesagt, diese Daten gibt es nur, wenn `context` konfiguriert wurde. Wenn wir den alten Weg entfernen, dann kann das natürlich immer gemacht werden.

Zusätzlich habe ich mir noch die Einbindung von anderen Templates angesehen. Es gibt nun einen speziellen Loader für das TYPO3 Filesystem. Damit kann man Templates innerhalb von Extensions und im fileadmin ansprechen. Der Namespace für den fileadmin ist `@fileadmin`. Die Extensions werden mit `@EXT:extName` angesprochen. In den Extensions müssen die Dateien immer unterhalb von `Resources/Private/` liegen. Dann kann man wieder frei wählen. Ist ausführlich [in der Doku](https://github.com/DMKEBUSINESSGMBH/typo3-t3twig/blob/c61f4851c4f74898c50078b031a9e33d50e834de/Documentation/reference/integration/namespaces.md) beschrieben.

**Comment by rengaw83** [comment]
Im [TwigContentObject](https://github.com/DMKEBUSINESSGMBH/typo3-t3twig/blob/e4fa9f94cbef06453df8e7f68a2efc4934cc2ea7/Classes/ContentObject/TwigContentObject.php#L120) sollten wirklich nur die Entsprechenden Daten aus dem Context gesetzt werden. Nicht auch die Page.

Die TSFE ist bereits von überall aus im Template verfügbar und damit auch die Page: `tsfe.page.alias`. Siehe [TsFeExtension](https://github.com/DMKEBUSINESSGMBH/typo3-t3twig/blob/3eb67b80cc2505cc8d1e6402e3e26baf8ebbd5ff/Classes/Twig/Extension/TsFeExtension.php#L57)

Ich habe das erst mal raus genommen. Ggf kann man die Page direkt in der Extension mit setzen, das wäre dann allerdings doppelt und man hätte nicht die Möglichkeit die variable page unter context zu setzen.

**Comment by RocKordier** [comment]
v1.0.0 was released several days ago. We can close for now, i think.
